apiVersion: apps/v1
kind: Deployment
metadata:
  name: computeserver-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: computeserver
  template:
    metadata:
      labels:
        app: computeserver
    spec:
      containers:
        - name: computeserver
          image: carlborhal/computeserverlatest
          ports:
            - containerPort: 9351
---
apiVersion: v1
kind: Service
metadata:
  name: computeserver-service
spec:
  selector:
    app: computeserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9351
  type: LoadBalancer